import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/shared/theme/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";

import {
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/shared/sidebar/AppSidebar";
import { createSupabaseServerClient } from "@/shared/utils/supabase/server";
import { Separator } from "@/components/ui/separator";
import { NavBreadcrumb } from "@/shared/sidebar/NavBreadcrumb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  const { data: userSecret } = await supabase
    .from("user_secrets")
    .select("id")
    .single();

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {user ? (
            <SidebarProvider
              style={
                {
                  "--sidebar-width": "calc(var(--spacing) * 72)",
                  "--header-height": "calc(var(--spacing) * 12)",
                } as React.CSSProperties
              }
            >
              <AppSidebar
                user={user}
                hasSetLlmApiKey={!!userSecret?.id}
                collapsible="icon"
              />
              <main className="w-full">
                <div className="flex items-center gap-2 px-4 border-b border-border h-12 sticky top-0 bg-background z-10">
                  <SidebarTrigger className="-ml-1" />
                  <Separator
                    orientation="vertical"
                    className="mr-2 data-[orientation=vertical]:h-4"
                  />
                  <NavBreadcrumb />
                </div>
                <div className="p-4">{children}</div>
              </main>
            </SidebarProvider>
          ) : (
            <>{children}</>
          )}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
